// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hyperledger-labs/minbft/messages/protobuf (interfaces: MessageWithUI,ReplicaMessage,ViewMessage)

// Package mock_protobuf is a generated GoMock package.
package mock_protobuf

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockMessageWithUI is a mock of MessageWithUI interface
type MockMessageWithUI struct {
	ctrl     *gomock.Controller
	recorder *MockMessageWithUIMockRecorder
}

// MockMessageWithUIMockRecorder is the mock recorder for MockMessageWithUI
type MockMessageWithUIMockRecorder struct {
	mock *MockMessageWithUI
}

// NewMockMessageWithUI creates a new mock instance
func NewMockMessageWithUI(ctrl *gomock.Controller) *MockMessageWithUI {
	mock := &MockMessageWithUI{ctrl: ctrl}
	mock.recorder = &MockMessageWithUIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMessageWithUI) EXPECT() *MockMessageWithUIMockRecorder {
	return m.recorder
}

// AttachUI mocks base method
func (m *MockMessageWithUI) AttachUI(arg0 []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AttachUI", arg0)
}

// AttachUI indicates an expected call of AttachUI
func (mr *MockMessageWithUIMockRecorder) AttachUI(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachUI", reflect.TypeOf((*MockMessageWithUI)(nil).AttachUI), arg0)
}

// EmbeddedMessages mocks base method
func (m *MockMessageWithUI) EmbeddedMessages() []interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmbeddedMessages")
	ret0, _ := ret[0].([]interface{})
	return ret0
}

// EmbeddedMessages indicates an expected call of EmbeddedMessages
func (mr *MockMessageWithUIMockRecorder) EmbeddedMessages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmbeddedMessages", reflect.TypeOf((*MockMessageWithUI)(nil).EmbeddedMessages))
}

// Payload mocks base method
func (m *MockMessageWithUI) Payload() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Payload")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Payload indicates an expected call of Payload
func (mr *MockMessageWithUIMockRecorder) Payload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Payload", reflect.TypeOf((*MockMessageWithUI)(nil).Payload))
}

// ReplicaID mocks base method
func (m *MockMessageWithUI) ReplicaID() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplicaID")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// ReplicaID indicates an expected call of ReplicaID
func (mr *MockMessageWithUIMockRecorder) ReplicaID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplicaID", reflect.TypeOf((*MockMessageWithUI)(nil).ReplicaID))
}

// UIBytes mocks base method
func (m *MockMessageWithUI) UIBytes() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UIBytes")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// UIBytes indicates an expected call of UIBytes
func (mr *MockMessageWithUIMockRecorder) UIBytes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UIBytes", reflect.TypeOf((*MockMessageWithUI)(nil).UIBytes))
}

// MockReplicaMessage is a mock of ReplicaMessage interface
type MockReplicaMessage struct {
	ctrl     *gomock.Controller
	recorder *MockReplicaMessageMockRecorder
}

// MockReplicaMessageMockRecorder is the mock recorder for MockReplicaMessage
type MockReplicaMessageMockRecorder struct {
	mock *MockReplicaMessage
}

// NewMockReplicaMessage creates a new mock instance
func NewMockReplicaMessage(ctrl *gomock.Controller) *MockReplicaMessage {
	mock := &MockReplicaMessage{ctrl: ctrl}
	mock.recorder = &MockReplicaMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockReplicaMessage) EXPECT() *MockReplicaMessageMockRecorder {
	return m.recorder
}

// EmbeddedMessages mocks base method
func (m *MockReplicaMessage) EmbeddedMessages() []interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmbeddedMessages")
	ret0, _ := ret[0].([]interface{})
	return ret0
}

// EmbeddedMessages indicates an expected call of EmbeddedMessages
func (mr *MockReplicaMessageMockRecorder) EmbeddedMessages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmbeddedMessages", reflect.TypeOf((*MockReplicaMessage)(nil).EmbeddedMessages))
}

// ReplicaID mocks base method
func (m *MockReplicaMessage) ReplicaID() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplicaID")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// ReplicaID indicates an expected call of ReplicaID
func (mr *MockReplicaMessageMockRecorder) ReplicaID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplicaID", reflect.TypeOf((*MockReplicaMessage)(nil).ReplicaID))
}

// MockViewMessage is a mock of ViewMessage interface
type MockViewMessage struct {
	ctrl     *gomock.Controller
	recorder *MockViewMessageMockRecorder
}

// MockViewMessageMockRecorder is the mock recorder for MockViewMessage
type MockViewMessageMockRecorder struct {
	mock *MockViewMessage
}

// NewMockViewMessage creates a new mock instance
func NewMockViewMessage(ctrl *gomock.Controller) *MockViewMessage {
	mock := &MockViewMessage{ctrl: ctrl}
	mock.recorder = &MockViewMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockViewMessage) EXPECT() *MockViewMessageMockRecorder {
	return m.recorder
}

// View mocks base method
func (m *MockViewMessage) View() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "View")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// View indicates an expected call of View
func (mr *MockViewMessageMockRecorder) View() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "View", reflect.TypeOf((*MockViewMessage)(nil).View))
}
