// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nec-blockchain/minbft/core/internal/peerstate (interfaces: State)

// Package mock_peerstate is a generated GoMock package.
package mock_peerstate

import (
	gomock "github.com/golang/mock/gomock"
	usig "github.com/nec-blockchain/minbft/usig"
	reflect "reflect"
)

// MockState is a mock of State interface
type MockState struct {
	ctrl     *gomock.Controller
	recorder *MockStateMockRecorder
}

// MockStateMockRecorder is the mock recorder for MockState
type MockStateMockRecorder struct {
	mock *MockState
}

// NewMockState creates a new mock instance
func NewMockState(ctrl *gomock.Controller) *MockState {
	mock := &MockState{ctrl: ctrl}
	mock.recorder = &MockStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockState) EXPECT() *MockStateMockRecorder {
	return m.recorder
}

// AcceptUI mocks base method
func (m *MockState) AcceptUI(arg0 *usig.UI) bool {
	ret := m.ctrl.Call(m, "AcceptUI", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AcceptUI indicates an expected call of AcceptUI
func (mr *MockStateMockRecorder) AcceptUI(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptUI", reflect.TypeOf((*MockState)(nil).AcceptUI), arg0)
}

// CommitUI mocks base method
func (m *MockState) CommitUI(arg0 *usig.UI) error {
	ret := m.ctrl.Call(m, "CommitUI", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitUI indicates an expected call of CommitUI
func (mr *MockStateMockRecorder) CommitUI(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitUI", reflect.TypeOf((*MockState)(nil).CommitUI), arg0)
}
