name: Continuous integration
on: [push, pull_request]
env:
  GOLANGCI_LINT_URL: https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
  SGX_MODE: SIM

jobs:
  build:
    name: Build with Go ${{ matrix.go }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        go: [1.16]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Install GolangCI-Lint
        run: |
          curl -sfL $GOLANGCI_LINT_URL | sudo sh -s -- -b /usr/local/bin
      - uses: actions/checkout@v2
      - name: Install Intel SGX SDK
        run: |
          sudo ./tools/install-sgx-sdk.sh
      - name: Test
        run: |
          source /opt/intel/sgxsdk/environment
          LD_LIBRARY_PATH="$PWD/usig/sgx/shim:$LD_LIBRARY_PATH" \
          GOFLAGS="-short" \
          make build check
      - name: Lint
        run: |
          make lint
